Graph generation
Vinicius-resende-cin/react-chrome-ext pull request #23
Opened 2024-10-29 22:30 UTC by ykarocin

2024-10-30 01:13 UTC, Vinicius-resende-cin requested changes

2024-10-30 01:13 UTC, Vinicius-resende-cin commented on src/extension/components/GraphVisualization.tsx
> +      data.y + data.size + (3 * LABEL_Y_OFFSET) + HOVER_PADDING// Adjust the offset to position label above the node
Acho que `3.5 * LABEL_Y_OFFSET` centraliza melhor a label

2024-10-30 01:13 UTC, Vinicius-resende-cin commented on src/extension/components/GraphVisualization.tsx
> +  const angleRadian = Math.asin(boxHeight / 2 / arcRadius);
Essa linha é necessária?

2024-10-31 00:59 UTC, ykarocin commented on src/extension/components/GraphVisualization.tsx
> +  const angleRadian = Math.asin(boxHeight / 2 / arcRadius);
qual linha exatamente?

2024-10-31 16:23 UTC, Vinicius-resende-cin commented on src/extension/components/GraphVisualization.tsx
> +  const angleRadian = Math.asin(boxHeight / 2 / arcRadius);
A 102

2024-10-31 16:24 UTC, Vinicius-resende-cin approved these changes

2024-10-31 16:24 UTC, merged